server.port: 9081

spring:
  application:
    name: kafka-store-streams
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  schema-registry-url: http://localhost:8081
  consumer:
    topic: mysql.storedb.orders
    num-partitions: 4
    auto-offset-reset: earliest
#  producer: