server.port: 9080

spring:
  application:
    name: store-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/storedb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: secret

logging.level:
  org.hibernate:
    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

load-samples:
  customers.enabled: true
  products.enabled: true

simulation:
  orders:
    total: 10
    sleep: 100
