server.port: 8081

spring:
  application:
    name: store-kafka-streams
  cloud:
    stream:
      bindings:
        input:
          destination: store-mysql-products
          consumer:
            nativeDecoding: true
            headerMode: raw
        output:
          destination: store-kafka-streams-products
          producer:
            nativeEncoding: true
            headerMode: raw
      kafka:
        streams:
          bindings:
            input:
              consumer:
                keySerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            output:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
          binder:
            brokers: localhost:29092
            configuration:
              schema.registry.url: http://localhost:8081
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
  health:
    binders:
      enabled: true