server.port: 9081

spring:
  application:
    name: store-streams
  cloud:
    stream:
      bindings:
        customer-input:
          destination: store-mysql-customers
          consumer:
            nativeDecoding: true
        product-input:
          destination: store-mysql-products
          consumer:
            nativeDecoding: true
        order-input:
          destination: store-mysql-orders
          consumer:
            nativeDecoding: true
        order-product-input:
          destination: store-mysql-orders_products
          consumer:
            nativeDecoding: true
        order-output:
          destination: store-streams-orders
          producer:
            nativeEncoding: true
      kafka:
        streams:
          bindings:
            customer-input:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.mycompany.storestreams.serde.CustomerSerde
                materializedAs: customer-ktable
            product-input:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.mycompany.storestreams.serde.ProductSerde
                materializedAs: product-ktable
            order-input:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
            order-product-input:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
            order-output:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
          binder:
            brokers: localhost:29092
            configuration:
              schema.registry.url: http://localhost:8081
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
  health:
    binders:
      enabled: true